# Generated by Django 2.2.6 on 2019-10-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'Not Done'), ('P', 'In Progress'), ('D', 'Done')], default='N', max_length=1)),
                ('story_points', models.FloatField()),
                ('effort_hours', models.FloatField()),
                ('summary', models.TextField(default='None')),
            ],
            options={
                'verbose_name': 'PBI',
                'verbose_name_plural': 'PBIs',
                'db_table': 'PBI',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PBI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.PBI')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Project')),
            ],
            options={
                'db_table': 'Product Backlog',
            },
        ),
        migrations.AddConstraint(
            model_name='productbacklog',
            constraint=models.UniqueConstraint(fields=('project', 'PBI'), name='project_PBI'),
        ),
    ]
