# Generated by Django 2.2.6 on 2019-10-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='summary',
            field=models.TextField(default=None),
        ),
    ]
