# Generated by Django 2.2.6 on 2019-10-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0002_auto_20191022_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backtrack.Project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductBacklog',
        ),
    ]
