# Generated by Django 2.2.6 on 2019-11-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0005_auto_20191101_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backtrack.Project'),
        ),
    ]
