# Generated by Django 2.2.6 on 2019-11-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0006_auto_20191101_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backtrack.Project'),
        ),
    ]
