# Generated by Django 2.2.6 on 2019-11-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0007_auto_20191101_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
