# Generated by Django 2.2.6 on 2019-11-02 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backtrack', '0008_auto_20191101_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SM', 'Scrum Master'), ('PO', 'Product Owner'), ('DT', 'Development Team')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='product_owner',
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='backtrack.Project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
