# Generated by Django 2.2.6 on 2019-11-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0009_auto_20191102_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Project'),
        ),
    ]
