# Generated by Django 2.2.6 on 2019-11-02 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0011_auto_20191102_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectParticipant', to='backtrack.Project'),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectParticipant', to='backtrack.Role'),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
