# Generated by Django 2.2.6 on 2019-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0012_auto_20191102_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipant',
            name='role',
            field=models.CharField(choices=[('SM', 'Scrum Master'), ('PO', 'Product Owner'), ('DT', 'Development Team')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
