# Generated by Django 2.2.6 on 2019-11-04 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backtrack', '0013_auto_20191102_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectParticipant', to='backtrack.Project', unique=True),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='role',
            field=models.CharField(choices=[('SM', 'Scrum Master'), ('PO', 'Product Owner'), ('DT', 'Development Team')], max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together={('user', 'project')},
        ),
    ]
