# Generated by Django 2.2.6 on 2019-11-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0015_auto_20191104_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipant',
            name='role',
            field=models.CharField(choices=[('SM', 'Scrum Master'), ('PO', 'Product Owner'), ('DT', 'Development Team')], max_length=2),
        ),
    ]
