# Generated by Django 2.2.6 on 2019-11-04 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0020_auto_20191104_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='backtrack.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
