# Generated by Django 2.2.6 on 2019-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0021_auto_20191104_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start',
            field=models.DateField(),
        ),
    ]
