# Generated by Django 2.2.6 on 2019-11-07 17:52

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0023_auto_20191107_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='N', max_length=50)),
                ('effort_hours', models.FloatField()),
                ('summary', models.TextField(default=None)),
                ('pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='backtrack.PBI')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_sprint', to='backtrack.Sprint')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
