# Generated by Django 2.2.6 on 2019-11-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0028_auto_20191109_0858'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
