# Generated by Django 2.2.6 on 2019-11-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0030_auto_20191122_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pbi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='backtrack.PBI'),
        ),
    ]
