# Generated by Django 2.2.6 on 2019-11-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0032_sprint_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('D', 'Developer'), ('M', 'Manager')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
